version: "3.9"

services:
  database_ignite:
    image: postgres
    container_name: database_rentcar
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentcar
      - POSTGRES_DB=rentcar
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentCar
    environment:
    - DATABASE_URL=postgresql://docker:rentcar@database_ignite:5432/rentcar?schema=public
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
